// <auto-generated> 
// THIS CODE IS AUTOMATICALLY GENERATED. DO NOT EDIT. 
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ServerCore.Packet;

namespace PacketGen
{
    public enum ProtocolId : ushort
    {
        C_HandshakeSyn = 1,
        S_HandshakeSynAck = 2,
        C_Login = 3,
        S_LoginResponse = 4,
        C_RequestWorldInfoArray = 5,
        S_WorldInfoArray = 6,
        C_RequestPlayerInfoArray = 7,
        S_PlayerInfoArray = 8,
        C_EnterZone = 9,
        S_EnterZoneResult = 10,
        S_SystemMessage = 11,
        C_Chat = 12,
        S_Chat = 13,
    }

    public enum ServerState : byte
    {
        Success,
        Failed,
        VersionMismatch,
        ServerMaintenance,
        UnknownError,
    }

    public enum ServerResult : byte
    {
        Success,
        Failed,
        DuplicateAuth,
        TryAgainLater,
        AdultOnly,
        Banned,
        UnknownError,
    }

    public enum PlatformType : byte
    {
        Windows,
        Android,
        IOS,
    }

    public class C_HandshakeSyn : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_HandshakeSyn;
        public int ClientVersion;
        public string DeviceId = string.Empty;
        public PlatformType PlatformType;

        public int GetMaxByteCount()
        {
            int size = 5;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(DeviceId.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt32(ClientVersion);
            w.WriteString(DeviceId);
            w.WriteUInt8((byte)PlatformType);
        }

        public void Deserialize(ref PacketReader r)
        {
            ClientVersion = r.ReadInt32();
            DeviceId = r.ReadString();
            PlatformType = (PlatformType)r.ReadUInt8();
        }
    }

    public class S_HandshakeSynAck : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_HandshakeSynAck;
        public DateTime ServerTime;
        public long EncryptionSeed;
        public ServerState ServerState;

        public int GetMaxByteCount()
        {
            int size = 17;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteDate(ServerTime);
            w.WriteInt64(EncryptionSeed);
            w.WriteUInt8((byte)ServerState);
        }

        public void Deserialize(ref PacketReader r)
        {
            ServerTime = r.ReadDate();
            EncryptionSeed = r.ReadInt64();
            ServerState = (ServerState)r.ReadUInt8();
        }
    }

    public class C_Login : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_Login;
        public string SessionToken = string.Empty;
        public long VerifySeed;

        public int GetMaxByteCount()
        {
            int size = 8;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(SessionToken.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteString(SessionToken);
            w.WriteInt64(VerifySeed);
        }

        public void Deserialize(ref PacketReader r)
        {
            SessionToken = r.ReadString();
            VerifySeed = r.ReadInt64();
        }
    }

    public class S_LoginResponse : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_LoginResponse;
        public ServerResult ServerResult;

        public int GetMaxByteCount()
        {
            int size = 1;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteUInt8((byte)ServerResult);
        }

        public void Deserialize(ref PacketReader r)
        {
            ServerResult = (ServerResult)r.ReadUInt8();
        }
    }

    public class C_RequestWorldInfoArray : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_RequestWorldInfoArray;

        public int GetMaxByteCount()
        {
            int size = 0;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
        }

        public void Deserialize(ref PacketReader r)
        {
        }
    }

    public class S_WorldInfoArray : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_WorldInfoArray;
        public ServerResult ServerResult;
        public WorldInfo[] WorldInfoArray = Array.Empty<WorldInfo>();

        public int GetMaxByteCount()
        {
            int size = 1;
            size += 4;
            foreach(var x in WorldInfoArray)
            {
                size += x.GetMaxByteCount();
            }
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteUInt8((byte)ServerResult);
            w.WriteInt32(WorldInfoArray.Length);
            foreach(var x in WorldInfoArray)
            {
                x.Serialize(ref w);
            }
        }

        public void Deserialize(ref PacketReader r)
        {
            ServerResult = (ServerResult)r.ReadUInt8();
            WorldInfoArray = new WorldInfo[r.ReadInt32()];
            for(int i = 0; i < WorldInfoArray.Length; i++)
            {
                WorldInfoArray[i] = new WorldInfo();
                WorldInfoArray[i].Deserialize(ref r);
            }
        }
    }

    public class WorldInfo : IStruct
    {
        public short WorldStaticId;
        public string WorldName = string.Empty;
        public int PlayerCount;
        public ChannelInfo[] ChannelInfoArray = Array.Empty<ChannelInfo>();

        public int GetMaxByteCount()
        {
            int size = 6;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(WorldName.Length);
            size += 4;
            foreach(var x in ChannelInfoArray)
            {
                size += x.GetMaxByteCount();
            }
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt16(WorldStaticId);
            w.WriteString(WorldName);
            w.WriteInt32(PlayerCount);
            w.WriteInt32(ChannelInfoArray.Length);
            foreach(var x in ChannelInfoArray)
            {
                x.Serialize(ref w);
            }
        }

        public void Deserialize(ref PacketReader r)
        {
            WorldStaticId = r.ReadInt16();
            WorldName = r.ReadString();
            PlayerCount = r.ReadInt32();
            ChannelInfoArray = new ChannelInfo[r.ReadInt32()];
            for(int i = 0; i < ChannelInfoArray.Length; i++)
            {
                ChannelInfoArray[i] = new ChannelInfo();
                ChannelInfoArray[i].Deserialize(ref r);
            }
        }
    }

    public class ChannelInfo : IStruct
    {
        public short ChannelIndex;
        public string ChannelName = string.Empty;
        public int PlayerCount;

        public int GetMaxByteCount()
        {
            int size = 6;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(ChannelName.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt16(ChannelIndex);
            w.WriteString(ChannelName);
            w.WriteInt32(PlayerCount);
        }

        public void Deserialize(ref PacketReader r)
        {
            ChannelIndex = r.ReadInt16();
            ChannelName = r.ReadString();
            PlayerCount = r.ReadInt32();
        }
    }

    public class C_RequestPlayerInfoArray : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_RequestPlayerInfoArray;
        public short WorldStaticId;

        public int GetMaxByteCount()
        {
            int size = 2;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt16(WorldStaticId);
        }

        public void Deserialize(ref PacketReader r)
        {
            WorldStaticId = r.ReadInt16();
        }
    }

    public class S_PlayerInfoArray : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_PlayerInfoArray;
        public ServerResult ServerResult;
        public PlayerInfo[] PlayerInfoArray = Array.Empty<PlayerInfo>();

        public int GetMaxByteCount()
        {
            int size = 1;
            size += 4;
            foreach(var x in PlayerInfoArray)
            {
                size += x.GetMaxByteCount();
            }
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteUInt8((byte)ServerResult);
            w.WriteInt32(PlayerInfoArray.Length);
            foreach(var x in PlayerInfoArray)
            {
                x.Serialize(ref w);
            }
        }

        public void Deserialize(ref PacketReader r)
        {
            ServerResult = (ServerResult)r.ReadUInt8();
            PlayerInfoArray = new PlayerInfo[r.ReadInt32()];
            for(int i = 0; i < PlayerInfoArray.Length; i++)
            {
                PlayerInfoArray[i] = new PlayerInfo();
                PlayerInfoArray[i].Deserialize(ref r);
            }
        }
    }

    public class PlayerInfo : IStruct
    {
        public short Index;
        public string Nickname = string.Empty;
        public int Level;
        public DateTime LastPlayedTime;

        public int GetMaxByteCount()
        {
            int size = 14;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(Nickname.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt16(Index);
            w.WriteString(Nickname);
            w.WriteInt32(Level);
            w.WriteDate(LastPlayedTime);
        }

        public void Deserialize(ref PacketReader r)
        {
            Index = r.ReadInt16();
            Nickname = r.ReadString();
            Level = r.ReadInt32();
            LastPlayedTime = r.ReadDate();
        }
    }

    public class C_EnterZone : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_EnterZone;
        public short WorldStaticId;
        public short ChannelIndex;
        public short PlayerIndex;

        public int GetMaxByteCount()
        {
            int size = 6;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt16(WorldStaticId);
            w.WriteInt16(ChannelIndex);
            w.WriteInt16(PlayerIndex);
        }

        public void Deserialize(ref PacketReader r)
        {
            WorldStaticId = r.ReadInt16();
            ChannelIndex = r.ReadInt16();
            PlayerIndex = r.ReadInt16();
        }
    }

    public class S_EnterZoneResult : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_EnterZoneResult;
        public ServerResult ServerResult;
        public int ZoneStaticId;

        public int GetMaxByteCount()
        {
            int size = 5;
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteUInt8((byte)ServerResult);
            w.WriteInt32(ZoneStaticId);
        }

        public void Deserialize(ref PacketReader r)
        {
            ServerResult = (ServerResult)r.ReadUInt8();
            ZoneStaticId = r.ReadInt32();
        }
    }

    public class S_SystemMessage : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_SystemMessage;
        public string Message = string.Empty;

        public int GetMaxByteCount()
        {
            int size = 0;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(Message.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteString(Message);
        }

        public void Deserialize(ref PacketReader r)
        {
            Message = r.ReadString();
        }
    }

    public class C_Chat : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.C_Chat;
        public string Chat = string.Empty;

        public int GetMaxByteCount()
        {
            int size = 0;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(Chat.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteString(Chat);
        }

        public void Deserialize(ref PacketReader r)
        {
            Chat = r.ReadString();
        }
    }

    public class S_Chat : IPacket, IStruct
    {
        public ushort Protocol => (ushort)ProtocolId.S_Chat;
        public long GameObjRuntimeId;
        public string Chat = string.Empty;

        public int GetMaxByteCount()
        {
            int size = 8;
            size += 4;
            size += Encoding.UTF8.GetMaxByteCount(Chat.Length);
            return size;
        }

        public void Serialize(ref PacketWriter w)
        {
            w.WriteInt64(GameObjRuntimeId);
            w.WriteString(Chat);
        }

        public void Deserialize(ref PacketReader r)
        {
            GameObjRuntimeId = r.ReadInt64();
            Chat = r.ReadString();
        }
    }
}
