// <auto-generated> 
// THIS CODE IS AUTOMATICALLY GENERATED. DO NOT EDIT. 
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ServerCore.Packet;

namespace PacketGen
{
    public static class PacketManager
    {
        private static class PacketWrapper<T> where T : IPacket
        {
            public static Action<PacketSession, T>? Handler;
        }

        private static readonly Dictionary<ProtocolId, Action<PacketSession, ArraySegment<byte>>> OnRecv = new();

        static PacketManager()
        {
            PacketWrapper<C_HandshakeSyn>.Handler = PacketHandler.C_HandshakeSyn_Handler;
            OnRecv.Add(ProtocolId.C_HandshakeSyn, MakePacket<C_HandshakeSyn>);
            PacketWrapper<C_Login>.Handler = PacketHandler.C_Login_Handler;
            OnRecv.Add(ProtocolId.C_Login, MakePacket<C_Login>);
            PacketWrapper<C_RequestWorldInfoArray>.Handler = PacketHandler.C_RequestWorldInfoArray_Handler;
            OnRecv.Add(ProtocolId.C_RequestWorldInfoArray, MakePacket<C_RequestWorldInfoArray>);
            PacketWrapper<C_RequestPlayerInfoArray>.Handler = PacketHandler.C_RequestPlayerInfoArray_Handler;
            OnRecv.Add(ProtocolId.C_RequestPlayerInfoArray, MakePacket<C_RequestPlayerInfoArray>);
            PacketWrapper<C_EnterZone>.Handler = PacketHandler.C_EnterZone_Handler;
            OnRecv.Add(ProtocolId.C_EnterZone, MakePacket<C_EnterZone>);
            PacketWrapper<C_Chat>.Handler = PacketHandler.C_Chat_Handler;
            OnRecv.Add(ProtocolId.C_Chat, MakePacket<C_Chat>);
        }

        public static void OnRecvPacket(PacketSession session, uint protocolId, ArraySegment<byte> payloadBuffer)
        {
            if (OnRecv.TryGetValue((ProtocolId)protocolId, out var action))
            {
                action.Invoke(session, payloadBuffer);
            }
            else
            {
                session.Disconnect($"Bad ProtocolId:{protocolId}");
            }
        }

        private static void MakePacket<T>(PacketSession session, ArraySegment<byte> buffer) where T : IPacket, IStruct, new()
        {
            var reader = new PacketReader(buffer);
            var packet = new T();
            packet.Deserialize(ref reader);

            PacketWrapper<T>.Handler?.Invoke(session, packet);
        }
    }
}
