using System.Text;

namespace PacketGen.CodeGenerator.CSharp
{
    public class CSharpPacketGen
    {
        private readonly List<Definition> _definitions;
        private readonly CSharpTypeProvider _typeProvider;
        private readonly GenOption _option;

        public CSharpPacketGen(List<Definition> definitions, GenOption option, TypeRegistry typeRegistry)
        {
            _option = option;
            _definitions = definitions;
            _typeProvider = new CSharpTypeProvider(definitions, typeRegistry);
        }

        public string Generate()
        {
            var sb = new StringBuilder();

            sb.Append
            (
$@"// <auto-generated> 
// THIS CODE IS AUTOMATICALLY GENERATED. DO NOT EDIT. 
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ServerCore.Packet;

namespace {_option.Namespace}
{{
"
            );

            GenerateProtocolIds(sb);

            foreach (var def in _definitions)
            {
                sb.AppendLine();
                switch (def)
                {
                    case EnumDefinition eDef:
                        GenerateEnum(sb, eDef);
                        break;
                    case StructDefinition sDef:
                        GenerateStruct(sb, sDef);
                        break;
                }
            }

            sb.AppendLine("}");
            return sb.ToString();
        }


        private static int StringToInt(string versionString)
        {
            if (string.IsNullOrEmpty(versionString)) return 0;

            string[] parts = versionString.Split('.');

            if (parts.Length != 4)
            {
                throw new FormatException($"Invalid version format: {versionString}. Expected format: '1.2.3.4'");
            }

            var major = int.Parse(parts[0]);
            var minor = int.Parse(parts[1]);
            var build = int.Parse(parts[2]);
            var revision = int.Parse(parts[3]);

            if (major > 255 || minor > 255 || build > 255 || revision > 255)
            {
                throw new OverflowException("Each version component must be between 0 and 255 for 32-bit packing.");
            }

            return (major << 24) | (minor << 16) | (build << 8) | revision;
        }

        private void GenerateProtocolIds(StringBuilder sb)
        {
            var packets = _definitions.OfType<PacketDefinition>().ToList();

            sb.AppendLine("    public enum ProtocolId : ushort");
            sb.AppendLine("    {");

            var assignedIds = new HashSet<long>();
            var rand = new Random();

            if (_option.IsProtocolRandomize)
            {
                var baseId = StringToInt(_option.Version) >> 8;
                var seed = (baseId * 397) ^ 0x5F3759DF;
                rand = new Random(seed);
            }

            foreach (var packet in packets)
            {
                long id;
                if (_option.IsProtocolRandomize)
                {
                    do
                    {
                        // 1 <= id < 65536
                        id = rand.Next(1, ushort.MaxValue + 1);
                    } while (!assignedIds.Add(id));
                }
                else
                {
                    id = assignedIds.Count + 1;
                    assignedIds.Add(id);
                }
                sb.AppendLine($"        {packet.Name} = {id},");
            }
            sb.AppendLine("    }");
        }

        private void GenerateEnum(StringBuilder sb, EnumDefinition def)
        {
            var ctx = _typeProvider.GetTypeContext(def.UnderlyingType);
            if (def.Attributes.Contains("flags")) sb.AppendLine("    [System.Flags]");

            sb.AppendLine($"    public enum {def.Name} : {ctx.Cs.CsTypeName}");
            sb.AppendLine("    {");
            foreach (var m in def.Members)
            {
                if (m.IsExplicit) sb.AppendLine($"        {m.Name} = {m.Value},");
                else sb.AppendLine($"        {m.Name},");
            }
            sb.AppendLine("    }");
        }

        private void GenerateStruct(StringBuilder sb, StructDefinition def)
        {
            var name = def.Name;
            var isPacket = def is PacketDefinition;
            var inheritance = isPacket ? " : IPacket, IStruct" : " : IStruct";

            sb.AppendLine($"    public class {name}{inheritance}");
            sb.AppendLine("    {");

            if (isPacket) sb.AppendLine($"        public ushort Protocol => (ushort)ProtocolId.{name};");

            foreach (var f in def.Fields) GenerateField(sb, f);

            sb.AppendLine();
            GenerateGetMaxByteCount(sb, def);
            sb.AppendLine();
            GenerateSerialize(sb, def);
            sb.AppendLine();
            GenerateDeserialize(sb, def);

            sb.AppendLine("    }");
        }

        private void GenerateField(StringBuilder sb, StructField f)
        {
            var ctx = _typeProvider.GetTypeContext(f.TypeName);
            var arrSuffix = f.IsArray ? "[]" : "";
            var init = f.IsArray ? $" = Array.Empty<{ctx.Cs.CsTypeName}>()" : "";
            if (!f.IsArray)
            {
                switch (ctx.Proto.Kind)
                {
                    case TypeKind.String: init = " = string.Empty"; break;
                    case TypeKind.Struct: init = $" = new {ctx.Cs.CsTypeName}()"; break;
                }
            }
            sb.AppendLine($"        public {ctx.Cs.CsTypeName}{arrSuffix} {f.Name}{init};");
        }

        private void GenerateGetMaxByteCount(StringBuilder sb, StructDefinition def)
        {
            sb.AppendLine("        public int GetMaxByteCount()");
            sb.AppendLine("        {");

            var fixedSize = 0;
            foreach (var f in def.Fields)
            {
                var ctx = _typeProvider.GetTypeContext(f.TypeName);
                if (!f.IsArray && ctx.Cs.SizeExpr is not null) fixedSize += ctx.Cs.SizeExpr.Value;
            }

            sb.AppendLine($"            int size = {fixedSize};");

            foreach (var f in def.Fields)
            {
                var ctx = _typeProvider.GetTypeContext(f.TypeName);
                if (!f.IsArray && ctx.Cs.SizeExpr is not null) continue;

                if (f.IsArray)
                {
                    sb.AppendLine($"            size += 4;");
                    switch (ctx.Proto.Kind)
                    {
                        case TypeKind.Primitive:
                        case TypeKind.Enum:
                        case TypeKind.DateTime:
                        case TypeKind.Guid:
                            sb.AppendLine($"            size += {f.Name}.Length * {ctx.Cs.SizeExpr};");
                            break;
                        case TypeKind.String:
                            sb.AppendLine($"            foreach(var x in {f.Name})");
                            sb.AppendLine("            {");
                            sb.AppendLine("                size += 4;");
                            sb.AppendLine("                size += Encoding.UTF8.GetMaxByteCount(x.Length);");
                            sb.AppendLine("            }");
                            break;
                        case TypeKind.Struct:
                            sb.AppendLine($"            foreach(var x in {f.Name})");
                            sb.AppendLine("            {");
                            sb.AppendLine("                size += x.GetMaxByteCount();");
                            sb.AppendLine("            }");
                            break;
                    }
                }
                else
                {
                    switch (ctx.Proto.Kind)
                    {
                        case TypeKind.String:
                            sb.AppendLine($"            size += 4;");
                            sb.AppendLine($"            size += Encoding.UTF8.GetMaxByteCount({f.Name}.Length);");
                            break;
                        case TypeKind.Struct:
                            sb.AppendLine($"            size += {f.Name}.GetMaxByteCount();");
                            break;
                    }
                }
            }
            sb.AppendLine("            return size;");
            sb.AppendLine("        }");
        }

        private void GenerateSerialize(StringBuilder sb, StructDefinition def)
        {
            sb.AppendLine("        public void Serialize(ref PacketWriter w)");
            sb.AppendLine("        {");
            foreach (var f in def.Fields)
            {
                var ctx = _typeProvider.GetTypeContext(f.TypeName);
                if (f.IsArray)
                {
                    if (ctx.Proto.Kind == TypeKind.Primitive || ctx.Proto.Kind == TypeKind.Enum)
                    {
                        sb.AppendLine($"            w.WriteArray<{ctx.Cs.CsTypeName}>({f.Name});");
                    }
                    else
                    {
                        sb.AppendLine($"            w.WriteInt32({f.Name}.Length);");
                        sb.AppendLine($"            foreach(var x in {f.Name})");
                        sb.AppendLine("            {");
                        if (ctx.Proto.Kind == TypeKind.Struct) sb.AppendLine($"                x.Serialize(ref w);");
                        else sb.AppendLine($"                w.{ctx.Cs.WriteMethod}(x);");
                        sb.AppendLine("            }");
                    }
                }
                else
                {
                    switch (ctx.Proto.Kind)
                    {
                        case TypeKind.Primitive:
                        case TypeKind.DateTime:
                        case TypeKind.String:
                        case TypeKind.Guid:
                            sb.AppendLine($"            w.{ctx.Cs.WriteMethod}({f.Name});"); break;
                        case TypeKind.Enum:
                            sb.AppendLine($"            w.{ctx.Cs.WriteMethod}(({ctx.Cs.CastType}){f.Name});"); break;
                        case TypeKind.Struct:
                            sb.AppendLine($"            {f.Name}.Serialize(ref w);"); break;
                    }
                }
            }
            sb.AppendLine("        }");
        }

        private void GenerateDeserialize(StringBuilder sb, StructDefinition def)
        {
            sb.AppendLine($"        public void Deserialize(ref PacketReader r)");
            sb.AppendLine("        {");
            foreach (var f in def.Fields)
            {
                var ctx = _typeProvider.GetTypeContext(f.TypeName);
                if (f.IsArray)
                {
                    if (ctx.Proto.Kind == TypeKind.Primitive || ctx.Proto.Kind == TypeKind.Enum)
                    {
                        sb.AppendLine($"            {f.Name} = r.ReadArray<{ctx.Cs.CsTypeName}>();");
                    }
                    else
                    {
                        sb.AppendLine($"            {f.Name} = new {ctx.Cs.CsTypeName}[r.ReadInt32()];");
                        sb.AppendLine($"            for(int i = 0; i < {f.Name}.Length; i++)");
                        sb.AppendLine("            {");
                        if (ctx.Proto.Kind == TypeKind.Struct)
                        {
                            sb.AppendLine($"                {f.Name}[i] = new {ctx.Cs.CsTypeName}();");
                            sb.AppendLine($"                {f.Name}[i].Deserialize(ref r);");
                        }
                        else
                        {
                            sb.AppendLine($"                {f.Name}[i] = r.{ctx.Cs.ReadMethod}();");
                        }
                        sb.AppendLine("            }");
                    }
                }
                else
                {
                    switch (ctx.Proto.Kind)
                    {
                        case TypeKind.Primitive:
                        case TypeKind.DateTime:
                        case TypeKind.String:
                        case TypeKind.Guid:
                            sb.AppendLine($"            {f.Name} = r.{ctx.Cs.ReadMethod}();"); break;
                        case TypeKind.Enum:
                            sb.AppendLine($"            {f.Name} = ({ctx.Cs.CsTypeName})r.{ctx.Cs.ReadMethod}();"); break;
                        case TypeKind.Struct:
                            sb.AppendLine($"            {f.Name} = new {ctx.Cs.CsTypeName}();");
                            sb.AppendLine($"            {f.Name}.Deserialize(ref r);"); break;
                    }
                }
            }
            sb.AppendLine("        }");
        }
    }
}