using System.Text;

namespace PacketGen.CodeGenerator.CSharp
{
    public class CSharpPacketManagerGen
    {
        private readonly List<Definition> _definitions;
        private readonly GenOption _option;

        public CSharpPacketManagerGen(List<Definition> definitions, GenOption option, TypeRegistry typeRegistry)
        {
            _option = option;
            _definitions = definitions;
        }

        public (string server, string client) Generate()
        {
            var packets = _definitions.OfType<PacketDefinition>().ToList();

            var serverPackets = packets
                .Where(p => p.Scope == PacketScope.Client || p.Scope == PacketScope.Both)
                .ToList();
            var serverCode = GenerateManagerCode(serverPackets);

            var clientPackets = packets
                .Where(p => p.Scope == PacketScope.Server || p.Scope == PacketScope.Both)
                .ToList();
            var clientCode = GenerateManagerCode(clientPackets);

            return (serverCode, clientCode);
        }

        private string GenerateManagerCode(List<PacketDefinition> targetPackets)
        {
            var sb = new StringBuilder();

            foreach (var packetDef in targetPackets)
            {
                sb.AppendLine($"            PacketWrapper<{packetDef.Name}>.Handler = PacketHandler.{packetDef.Name}_Handler;");
                sb.AppendLine($"            OnRecv.Add(ProtocolId.{packetDef.Name}, MakePacket<{packetDef.Name}>);");
            }

            var code =
        $@"// <auto-generated> 
// THIS CODE IS AUTOMATICALLY GENERATED. DO NOT EDIT. 
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ServerCore.Packet;

namespace {_option.Namespace}
{{
    public static class PacketManager
    {{
        private static class PacketWrapper<T> where T : IPacket
        {{
            public static Action<PacketSession, T>? Handler;
        }}

        private static readonly Dictionary<ProtocolId, Action<PacketSession, ArraySegment<byte>>> OnRecv = new();

        static PacketManager()
        {{
{sb}        }}

        public static void OnRecvPacket(PacketSession session, uint protocolId, ArraySegment<byte> payloadBuffer)
        {{
            if (OnRecv.TryGetValue((ProtocolId)protocolId, out var action))
            {{
                action.Invoke(session, payloadBuffer);
            }}
            else
            {{
                session.Disconnect($""Bad ProtocolId:{{protocolId}}"");
            }}
        }}

        private static void MakePacket<T>(PacketSession session, ArraySegment<byte> buffer) where T : IPacket, IStruct, new()
        {{
            var reader = new PacketReader(buffer);
            var packet = new T();
            packet.Deserialize(ref reader);

            PacketWrapper<T>.Handler?.Invoke(session, packet);
        }}
    }}
}}
";
            return code;
        }
    }
}